version: '3'
services:
  mysql:
    build:
      context: ./mysql      
      dockerfile: Dockerfile
    container_name: mysql-8.0.33
    hostname: mysql-8.0.33
    networks:
      - mysql-java
    #   this container should communicate only with hello-java
 #   ports:
 #     - '3306:3306' 
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  hello-java:
    container_name: hello-java
    build:
      context: ./hello-java
      dockerfile: Dockerfile
    networks:
      - mysql-java
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: my-nginx
    networks:
      - mysql-java
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-logs:/var/log/nginx
    depends_on: 
      - hello-java

networks:
  mysql-java:
    name: mysql-java
    driver: bridge
