version: '3'
services:
  hello-db:
    build:
      context: ./hello-db
      dockerfile: Dockerfile
    container_name: hello-db
    networks:
      - hello-network
 #   hello-db should communicate only with hello-server
#    ports:
#      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  hello-server:
    container_name: hello-server
    build:
      context: ./hello-server
      dockerfile: Dockerfile
    networks:
      - hello-network
    ports:
      - '8080:8080'
    depends_on:
      - hello-db

  nginx:
    image: nginx
    container_name: hello-nginx
    networks:
      - hello-network
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-logs:/var/log/nginx
    depends_on: 
      - hello-server

networks:
  hello-network:
    name: hell-network
    driver: bridge
